package com.backend.entities;

public enum ApplicationStatus {
    PENDING_STAFF_APPROVAL,
    DOCUMENTS_REQUESTED,
    DOCUMENTS_SUBMITTED,
    DOCUMENTS_VERIFIED,
    WELFARE_VISIT_SCHEDULED,
    WELFARE_VISIT_COMPLETED,
    APPROVED,
    REJECTED
}