// Application Status Constants
export const APPLICATION_STATUS = {
  PENDING_STAFF_APPROVAL: "PENDING_STAFF_APPROVAL",
  DOCUMENTS_REQUESTED: "DOCUMENTS_REQUESTED", 
  DOCUMENTS_SUBMITTED: "DOCUMENTS_SUBMITTED",
  STAFF_VERIFIED: "STAFF_VERIFIED",
  PENDING_ADMIN_APPROVAL: "PENDING_ADMIN_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED"
};

// Child Status Constants
export const CHILD_STATUS = {
  AVAILABLE: "AVAILABLE",
  IN_APPLICATION: "IN_APPLICATION", 
  ADOPTED: "ADOPTED"
};

// Document Status Constants
export const DOCUMENT_STATUS = {
  PENDING: "PENDING",
  SUBMITTED: "SUBMITTED",
  STAFF_VERIFIED: "STAFF_VERIFIED",
  ADMIN_APPROVED: "ADMIN_APPROVED",
  REJECTED: "REJECTED"
};